#
# Set up travis with:
# env vars:
# - HEROKU_AUTH_TOKEN from: heroku authorizations:create -d "travis-ci for hsl-members-api"
# - HEROKU_APP either hsl-members-api-staging (for master) or hsl-members-api (for production)
#

language: generic

services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com

install:
  - cp docker-compose.dist.yml docker-compose.yml #&& sed -i "s^/home/YOUR_USER/YOUR_PATH/THIS_FOLDER^`pwd`^g" docker-compose.yml
  - docker-compose up -d

script:
  - docker exec -it members_ui sh -c 'wget -q -O - localhost:3005 && echo "SUCCESS"'

before_deploy:
  - docker tag ui_members_ui:latest registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script: docker push registry.heroku.com/$HEROKU_APP/web && HEROKU_API_KEY=$HEROKU_AUTH_TOKEN heroku container:release web -a $HEROKU_APP
  on:
    branch: master