version: "3"
services:
  members_ui:
    container_name: members_ui
    build: .
    ports:
      - "3005:3005" # Currently in package.json we only start with PORT=3005
    environment:
      NODE_ENV: "development"
      REACT_APP_MEMBERS_API_URL: "http://localhost:3004" # use what's visible from the host machine
